export const fakultas = [
  //   {
  //     id: 1,
  //     kode: "FSH",
  //     nama: "Syariah dan Hukum",
  //     singkatan: "FSH",
  //     prodi: [
  //       { id: 1, kode: "HI", nama: "Hukum Islam", jenjangId: 2, fakultasId: 1 },
  //       { id: 2, kode: "MUAMALAH", nama: "Muamalah", jenjangId: 2, fakultasId: 1 },
  //       { id: 3, kode: "JINAYAH", nama: "Jinayah", jenjangId: 2, fakultasId: 1 },
  //     ],
  //   },
  {
    id: 2,
    kode: "FITK",
    nama: "Ilmu Tarbiyah dan Keguruan",
    singkatan: "FITK",
    prodi: [
      { id: 4, kode: "PAI", nama: "Pendidikan Agama Islam", jenjangId: 2, fakultasId: 2 },
      { id: 5, kode: "PBI", nama: "Pendidikan Bahasa Inggris", jenjangId: 2, fakultasId: 2 },
      { id: 6, kode: "PBA", nama: "Pendidikan Bahasa Arab", jenjangId: 2, fakultasId: 2 },
      { id: 7, kode: "PGMI", nama: "Pendidikan Guru Madrasah Ibtidaiyah", jenjangId: 2, fakultasId: 2 },
      { id: 8, kode: "PMTK", nama: "Pendidikan Matematika", jenjangId: 2, fakultasId: 2 },
      { id: 9, kode: "PBIO", nama: "Pendidikan Biologi", jenjangId: 2, fakultasId: 2 },
      { id: 10, kode: "MPI", nama: "Manajemen Pendidikan Islam", jenjangId: 2, fakultasId: 2 },
      { id: 11, kode: "PKIM", nama: "Pendidikan Kimia", jenjangId: 2, fakultasId: 2 },
      { id: 12, kode: "PFIS", nama: "Pendidikan Fisika", jenjangId: 2, fakultasId: 2 },
      { id: 13, kode: "PIAUD", nama: "Pendidikan Islam Anak Usia Dini", jenjangId: 2, fakultasId: 2 },
      { id: 14, kode: "MPAI", nama: "Magister Pendidikan Agama Islam", jenjangId: 3, fakultasId: 2 },
      { id: 15, kode: "MMPI", nama: "Magister Manajemen Pendidikan Islam", jenjangId: 3, fakultasId: 2 },
    ],
  },
  {
    id: 3,
    kode: "FU",
    nama: "Ushuluddin dan Pemikiran Islam",
    singkatan: "FU",
    prodi: [
      { id: 16, kode: "SAA", nama: "Studi Agama-Agama", jenjangId: 2, fakultasId: 3 },
      { id: 17, kode: "IAT", nama: "Ilmu al-Quran dan Tafsir", jenjangId: 2, fakultasId: 3 },
      { id: 18, kode: "IH", nama: "Ilmu Hadis", jenjangId: 2, fakultasId: 3 },
      { id: 19, kode: "TP", nama: "Tasawuf dan Psikoterapi", jenjangId: 2, fakultasId: 3 },
      { id: 20, kode: "MIAT", nama: "Magister Ilmu al-Quran dan Tafsir", jenjangId: 3, fakultasId: 3 },
      { id: 21, kode: "AFI", nama: "Aqidah dan Filsafat Islam", jenjangId: 2, fakultasId: 3 },
    ],
  },
  {
    id: 4,
    kode: "FAH",
    nama: "Adab dan Humaniora",
    singkatan: "FAH",
    prodi: [
      { id: 22, kode: "BSA", nama: "Bahasa dan Sastra Arab", jenjangId: 2, fakultasId: 4 },
      { id: 23, kode: "SPI", nama: "Sejarah Peradaban Islam", jenjangId: 2, fakultasId: 4 },
      { id: 24, kode: "IP", nama: "Ilmu Perpustakaan", jenjangId: 2, fakultasId: 4 },
      { id: 25, kode: "IPI", nama: "Ilmu Politik Islam", jenjangId: 2, fakultasId: 4 },
    ],
  },
  {
    id: 5,
    kode: "FDK",
    nama: "Dakwah dan Komunikasi",
    singkatan: "FDK",
    prodi: [
      { id: 26, kode: "BPI", nama: "Bimbingan Penyuluhan Islam", jenjangId: 2, fakultasId: 5 },
      { id: 27, kode: "JUR", nama: "Jurnalistik", jenjangId: 2, fakultasId: 5 },
      { id: 28, kode: "KPI", nama: "Komunikasi Penyiaran Islam", jenjangId: 2, fakultasId: 5 },
      { id: 29, kode: "MD", nama: "Manajemen Dakwah", jenjangId: 2, fakultasId: 5 },
      { id: 30, kode: "PMI", nama: "Pengembangan Masyarakat Islam", jenjangId: 2, fakultasId: 5 },
    ],
  },
  {
    id: 6,
    kode: "FEBI",
    nama: "Ekonomi dan Bisnis Islam",
    singkatan: "FEBI",
    prodi: [
      { id: 31, kode: "PS", nama: "Perbankan Syariah", jenjangId: 2, fakultasId: 6 },
      { id: 32, kode: "ES", nama: "Ekonomi Syariah", jenjangId: 2, fakultasId: 6 },
      { id: 33, kode: "MZW", nama: "Manajemen Zakat dan Wakaf", jenjangId: 2, fakultasId: 6 },
      { id: 34, kode: "MES", nama: "Magister Ekonomi Syariah", jenjangId: 3, fakultasId: 6 },
    ],
  },
  {
    id: 7,
    kode: "FISIP",
    nama: "Ilmu Sosial dan Ilmu Politik",
    singkatan: "FISIP",
    prodi: [
      { id: 35, kode: "IP", nama: "Ilmu Politik", jenjangId: 2, fakultasId: 7 },
      { id: 36, kode: "IKOM", nama: "Ilmu Komunikasi", jenjangId: 2, fakultasId: 7 },
    ],
  },
  {
    id: 8,
    kode: "FST",
    nama: "Sains dan Teknologi",
    singkatan: "FST",
    prodi: [
      { id: 37, kode: "SI", nama: "Sistem Informasi", jenjangId: 2, fakultasId: 8 },
      { id: 38, kode: "BIO", nama: "Biologi", jenjangId: 2, fakultasId: 8 },
      { id: 39, kode: "KIM", nama: "Kimia", jenjangId: 2, fakultasId: 8 },
    ],
  },
  {
    id: 9,
    kode: "FPsi",
    nama: "Psikologi",
    singkatan: "FPsi",
    prodi: [{ id: 40, kode: "PSI", nama: "Psikologi", jenjangId: 2, fakultasId: 9 }],
  },
  {
    id: 10,
    kode: "PPs",
    nama: "Pascasarjana",
    singkatan: "PPs",
    prodi: [
      { id: 41, kode: "DPAI", nama: "Doktor Pendidikan Agama Islam", jenjangId: 4, fakultasId: 10 },
      { id: 42, kode: "DPI", nama: "Doktor Peradaban Islam", jenjangId: 4, fakultasId: 10 },
      { id: 43, kode: "MSI", nama: "Magister Studi Islam", jenjangId: 3, fakultasId: 10 },
    ],
  },
];
